setup.php
1. Incompatibility message was displayed twice on GLPI 9.2+.
2. Use of constants to make update of compatibility easier.
3. Use of max requirement to prevent installation on untested version.
=> Fix version compatibility check

inc/commoninjectionlib.class.php
"Search options to add" are not indexed anymore by their id in GLPI 9.3. Values added to backlist were so from "1" to "count of values - 1" instead of search options ids.
=> Fix allowed fields in mapping; fixes #103

datainjection.xml
Ordered alphabetically for correct sorting when displayed on plugins.glpi-project.org
Revised list of languages to present only translations, that are at least from 50% done on Transifex (to don't confuse users about true availability in their languages).
Minor tweaks in Czech translation.
Fixed typo in English description.
=> Tweaked datainjection.xml

inc/model.class.php
PR for fix   #109 
redefine url for genericobject objet on injection reports
=> fix(report): fix bad url on generic object on report after injection

inc/commoninjectionlib.class.php
Preserve only one option per linkfield, as mapping process is based on arrays indexed by linkfield.
This is a hack to handle behaviour explained in issue https://github.com/pluginsGLPI/datainjection/issues/121.
From most preferred to less desirable, the option chosen for each linkfield is:
"completename", else "name", else first option found
=> Prefer "complete[name]" field for mapping with tier item; see #121

docs/README.txt, front/clientinjection.form.php, front/popup.php, inc/clientinjection.class.php, inc/menu.class.php, inc/model.class.php, inc/profile.class.php, setup.php
- Rename "File injection" to "Data injection", closes #143 
- Improve warning text on model creation (internal 17549)
- The "Watch out..." text was never displayed (incorrect condition)
- The "Watch out..." text was not correctly escaped and didn't work (javascript error)
**Need to regenerate translations.**
=> fix: improve menu titles and warning messages

inc/model.class.php
Required to enable autocomplete on GLPI 9.4.4+ (see https://github.com/glpi-project/glpi/commit/339b856273f2cf5cb409e6db1a2689a418c5a051)
=> Whitelist autocomplete fields

inc/model.class.php
On validate model this warning show up
```
==> ../../files/_log/sql-errors.log <==
[2020-03-03 08:32:39] glpisqllog.ERROR: DBmysql::query() in /home/stanislas/Teclib/dev/GLPI/9.4-bugfixes/inc/dbmysql.class.php line 188
*** MySQL query error:
SQL: UPDATE `glpi_plugin_datainjection_models` SET `name` = 'test d'utilisateurdd' WHERE `id` = '7'
Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'utilisateurdd' WHERE `id` = '7'' at line 1
Backtrace :
inc/dbmysql.class.php:948                          
inc/commondbtm.class.php:616                       DBmysql->update()
inc/commondbtm.class.php:1444                      CommonDBTM->updateInDB()
plugins/datainjection/inc/model.class.php:1251 …
```
=> fix(core): add slashes deep when validate model

inc/computerinjection.class.php
this fix bad translation for computer fields 
list diplay two 'name' one for computer, other for antivirus
this PR fix this
=> fix(core): overload translation for antiviruse name

.travis.yml, composer.json, composer.lock, datainjection.xml, hook.php, inc/clientinjection.class.php, inc/commoninjectionlib.class.php, inc/entityinjection.class.php, inc/info.class.php, inc/injectiontype.class.php, inc/mapping.class.php, inc/menu.class.php, inc/model.class.php, inc/networkportinjection.class.php, inc/profile.class.php, setup.php, testwebservice.php
With this PR, plugin should be compatible with GLPI 9.5.
Remaining work to do:
=> Add GLPI 9.5 compatibility

inc/commoninjectionlib.class.php
Relation injection (ie : Contact_Supplier) is break.
SearchOption typed as 'relation' are managed two times by
- manageRelations function
- manageFieldValues function
Now manageFieldValues exclude  saerchoption typed as 'relation'
manageRelations try to clean old values, but clean data newly calculated -> fixed too
internal 20623
=> fix(injection): fix relation injection

inc/commoninjectionlib.class.php
Since glpi-project/glpi#8816, there was a second search option with the same "users_id" link field. Then in the workaround for #121, the correct `User` option gets removed and the `Appliance User` option remains. This remaining option isn't injectable though and is dropped later anyways. It makes sense to drop all non-injectable options before the workaround.
fixes #259
fixes #243
fixes #233
=> Drop not injectable fields before single linkfield workaround

inc/commoninjectionlib.class.php
Preserve ```entities_id``` (droped because related ```searchoption``` is blacklisted)
To prevent this error :
```shell
[2022-03-30 16:14:49] glpiphplog.NOTICE:   *** PHP Notice (8): Trying to access array offset on value of type bool in /home/stanislas/Teclib/dev/GLPI/plugins/datainjection/inc/commoninjectionlib.class.php at line 1518
Backtrace :
...injection/inc/commoninjectionlib.class.php:1453 PluginDatainjectionCommonInjectionLib->effectiveAddOrUpdate()
...s/datainjection/inc/phoneinjection.class.php:87 PluginDatainjectionCommonInjectionLib->processAddOrUpdate()
plugins/datainjection/inc/engine.class.php:147     PluginDatainjectionPhoneInjection->addOrUpdateObject()
...datainjection/inc/clientinjection.class.php:267 PluginDatainjectionEngine->injectLine() …
```
=> fix(datainjection): preserve entities_id

inc/commoninjectionlib.class.php, inc/engine.class.php
Try to repair "fields implementation"
Preserve ```itemtype``` and ```items_id``` when injected class is from ```fields``` plugin
=> fix(datainjection): restore fields implementation

setup.php
`$_SERVER['REQUEST_URI']` wont be defined in a CLI context (install from cli, cron execution, ...).
=> Fix CLI warnings

inc/itilcategoryinjection.class.php
CSV file:
The goal is to find a category using its completename and update its parent category.
Model:
The import does not work (parent category is set to null):
It seems like the "Father" search option is not declared as a dropdown.
After adding the searchoption's id (13) to the dropdown list, the import work as expected:
=> ITILCategories: fix set parent category

inc/commoninjectionlib.class.php
Using this simple CSV file containing users login and emails (imagine real emails instead of **** 😅):
The goal is, for each row, to find the user with the matching email and update its login.
Here is the model we are using:
The import will fail because datainjection doesn't seem to handle users search by email very well:
The query has no chance to succeed as it is looking for a foreign key that doesn't exist (and with an incorrect value - the raw email wouldn't be a valid foreign key anyway):
```sql
SELECT * FROM `glpi_users` WHERE 1 AND `is_deleted` = '0' AND `useremails_id`='*****@*****'
```
The correct query would be:
```sql
SELECT * FROM `glpi_users` WHERE 1 AND `is_deleted` = '0' AND `id` IN (
SELECT `user_id` FROM glpi_useremails WHERE `email` = '*****@*****'
);
```
To fix this, …
=> Fix search user by email

inc/commoninjectionlib.class.php, inc/contract_iteminjection.class.php
fix DBRelation injection (retrieve missing field from relation)
change relation side from ```contract_iteminjection``` to prevent SQL error
```sql
[2022-06-08 19:19:39] glpisqllog.ERROR: DBmysql::query() in C:\laragon\www\glpi\inc\dbmysql.class.php line 335
*** MySQL query error:
SQL: SELECT *
FROM `glpi_contracts_items` WHERE 1 AND `contracts_id`='104' AND `Contract`='' AND `items_id`='33'
Error: Unknown column 'Contract' in 'where clause'
Backtrace :
...injection\inc\commoninjectionlib.class.php:1827
...injection\inc\commoninjectionlib.class.php:1476 PluginDatainjectionCommonInjectionLib->dataAlreadyInDB()
...tainjection\inc\computerinjection.class.php:101 PluginDatainjectionCommonInjectionLib->processAddOrUpdate()
plugins\datainjection\inc\engine.class.php:147 …
```
=> fix(injection): fix DBRelation injection

inc/commoninjectionlib.class.php
The injection process is based on the order of the columns in the CSV file
Which can be annoying in some cases
We need to move item before another
Ex : NetworkPort before NetworkName
it's ugly ! we agree, but I have no other solution for the moment
=> move item order from array if needed

inc/commoninjectionlib.class.php
Line breaks in a multiline field (e.g. comment) were lost and replaced by `n` or `rn`:
Internal reference : !24858
=> fix(import): carriage return

inc/commoninjectionlib.class.php
Try to fix certain cases of imports such as a Group import that includes a group member field.
Commit 69748585a43a5d73aa4a0a061d0e519b97b943ed had broken this type of import because `effectiveAddOrUpdate` would receive an `itemtype` and `items_id` value which were not valid search options, but were still required for the import to work.
This patch seems to resolve this particular issue although I don't know if it will cause other issues.
=> Fix group user import

inc/tasktemplateinjection.class.php
Fix ```searchoption``` not declared as ```dropdown``` 
like ```https://github.com/pluginsGLPI/datainjection/pull/323/commits/df6809d689978ace00da29d0e294ee09035b748e```
Prevent SQL error 
```sql
Incorrect integer value: 'Internet' for column `10bugfixes`.`glpi_tasktemplates`.`taskcategories_id` at row 1
```
++
=> fix(injection): declare searchoption as dropdown type

inc/commoninjectionlib.class.php
as discussed here -> https://github.com/pluginsGLPI/datainjection/pull/330#issuecomment-1464085877
> For labels, we could maybe add a "($itemtype)" suffix when field refers to a distinct object table, e.g. "Name (Domain)".
=> feat(mapping): best distinction for the fields

inc/applianceinjection.class.php
Add `Group` and `Group in charge` search options to the dropdown list for Appliances.
With this fix, they will be able to be imported by their names instead of using raw databases ids.
=> Fix import of appliances groups

inc/budgetinjection.class.php
Certain fields of the budget were badly controlled, causing the import to fail.
Example:
Internal ref.: !30243
=> fix budget checktype

inc/item_operatingsysteminjection.class.php
When importing computers with DataInjection, the operating system is added, not replaced. This results in 2 or more OS per computer, which should even not be possible in GLPI.
This PR fix this
fix : internal ref : 30448
=> fix(Item_Operatingsystem): update / handle one OS like GLPI

inc/commoninjectionlib.class.php
When an object is dynamic and a field is locked (manually updated)
Datainjection cannot also update this field
This PR fix this
#342
=> fix(injection): allow lockedfield update

CHANGELOG.md, hook.php
When the user does not have a model (```private``` or ```public```), the plugin loads all models.
This PR fixes this problem by adding a where clause that will force a query to return no results (fake comparison)
Fix https://github.com/pluginsGLPI/datainjection/issues/352
=> fix(Model): fix model visibility

CHANGELOG.md, inc/model.class.php
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !34299
After some discussion, it was removed because he thought that the port uniqueness option depended on ‘perform_network_connection’ (which was an unused option) when it didn't
=> Fix port unicity

CHANGELOG.md, inc/commoninjectionlib.class.php
Since https://github.com/pluginsGLPI/datainjection/pull/303
`IPAddress` injection no longer work and adds lock for `date_mod` fields
The reordering of the `array` is a bit violent (put `NetworkPort` at the beginning).
Here's a better solution (put `NetworkPort` just before `NetworkName`) because to manage the `IPAddress`, the `NetworkPort` must be managed beforehand
fix !34426
=> Fix(Injection): prevent locked date_mod field

CHANGELOG.md, inc/commoninjectionlib.class.php
When a dynamic `asset` is update by plugin
link with agent is lost (`Agent` is not deleted, it's the `asset` that's no longer dynamic ```is_dynamic = 0```)
Fix #413
=> Fix(Injection): prevent Agent deletion on update dynamic object

CHANGELOG.md, inc/commoninjectionlib.class.php, inc/engine.class.php, inc/model.class.php, inc/userinjection.class.php
- It fixes !34752
Fix default entity insertion for a user
=> Fix user default entity injection

inc/backend.class.php, inc/backendcsv.class.php
```
glpiphplog.NOTICE:   *** PHP Deprecated function (8192): Function utf8_encode() is deprecated in /home/ubuntu/Dev/GLPI/10.0-bugfixes/plugins/datainjection/inc/backend.class.php at line 108
Backtrace :
plugins/datainjection/inc/backendcsv.class.php:118 PluginDatainjectionBackend::toUTF8()
plugins/datainjection/inc/backendcsv.class.php:247 PluginDatainjectionBackendcsv::parseLine()
...datainjection/inc/clientinjection.class.php:299 PluginDatainjectionBackendcsv->getNextLine()
...datainjection/inc/clientinjection.class.php:226 PluginDatainjectionClientInjection::processInjection()
...datainjection/front/clientinjection.form.php:45 PluginDatainjectionClientInjection::showInjectionForm()
public/index.php:82 …
```
=> fix: deprecated function utf8_encode

CHANGELOG.md, inc/model.class.php
- It fixes #371 
- Here is a brief description of what this PR does: When loading the form to add a new injection model the DB is queried multiple times by the checkRightOnModel() function with  `""` as the `$models_id` (since no model is being selected).  This throws multiple errors of
```
SQL Warnings: 1292: Truncated incorrect DECIMAL value: '' in query "(SELECT `itemtype` FROM `glpi_plugin_datainjection_models` WHERE `id` = '') UNION (SELECT DISTINCT `itemtype` FROM `glpi_plugin_datainjection_mappings` WHERE `models_id` = '') UNION (SELECT DISTINCT `itemtype` FROM `glpi_plugin_datainjection_infos` WHERE `models_id` = '')"
```
This change sets it to `-1` when null in order to feed a valid value into the query. 
I've confirmed that existing …
=> Fix for issue #371

CHANGELOG.md, inc/commoninjectionlib.class.php
I encountered an issue when trying to import software licenses where most dropdown fields were attempting to inject the text value in the import file rather than the foreign ID from the corresponding table. This was traced back to there being missing dropdown IDs in `softwarelicenseinjection.class.php`, Adding the missing IDs fixed this for injecting software licenses, however, there was no way to know if there were missing items in other classes.
I saw these options in the injection class were being used to set the `displaytype` of dropdown, which is later used to determine if a foreign table relation needed to be made. Rather than adding these manually, I've made a change to set the `displaytype` of `dropdown` from the rawSearchOptions that …
=> Fix for Missing Dropdown Options

CHANGELOG.md, hook.php, inc/commoninjectionlib.class.php, inc/engine.class.php, inc/model.class.php
- If a new value for a multiline_text field starts with "#replace", the old value is completely replaced instead of being concatenated.
- The "#replace" tag is removed before storing the new value.
- Default behavior remains unchanged for other cases.
- It fixes #438 
- This PR modifies the behavior of multiline_text fields:
- If a new value starts with #replace, the old value is completely replaced instead of being concatenated.
- The #replace tag is removed before storing the new value.
- The default concatenation behavior remains unchanged when the tag is not present.
=> Fix: Replace multiline_text fields when prefixed with #replace

front/export.csv.php, front/export.pdf.php, front/info.form.php, front/mapping.form.php, front/model.form.php, front/model.php
=> Fix: front/ check

CHANGELOG.md, inc/commoninjectionlib.class.php
- It fixes !38104
Previously, it was possible to add a single note to an element, but now it's possible to add several. However, since note management has been modified to integrate this functionality, importing is not possible on the element side, and this causes the rest of the injection to crash. It must be added by importing notes directly.
=> Add notes search option in BlacklistedOptions

CHANGELOG.md, inc/commoninjectionlib.class.php
- It fixes !38252
- The ‘pdffont’ field belongs to the glpi_users table and is used to select the desired font for PDF export. This field is not directly modifiable in the user form, but in the user's personal preferences. This means that each time a user is imported, this non-blocking error appears when viewing the import report, as the ‘pdffont’ field is never available during import.
=> fix(User): Error modal generated by “pdffont” field

CHANGELOG.md, hook.php
- It fixes !39063
- When an update to the datainjection plugin is performed, the message “Task completed” is displayed once it is finished. This fix removes this message because it is only present for this plugin.
=> fix(migration): remove Task completed message during plugin update
