inc/commoninjectionlib.class.php
inc/notepadinjection.class.php
setup.php

add notepad

---

hook.php

Bug introduced in commit https://github.com/pluginsGLPI/datainjection/commit/78b93c3fa3a6dbdb3472417299b54db1c0412f55

Fix profile migration; fixes #86

---

hook.php

I introduced a bug in commit eb4646efbf9eec35af39d0e238989a260ebdc588.
Test was made in Adminer UI, bad idea !

Fixes eb4646efbf9eec35af39d0e238989a260ebdc588

---

datainjection.xml

Added short and long description in Czech language, as well as keywords.

l10n - added Czech translation into xml

---

datainjection.xml
hook.php
setup.php

- Handle renaming of "licence_id" field of "glpi_items_operatingsystems"
- Handle renaming of "glpi_ticketfollowups" table to "glpi_itilfollowups"

GLPI 9.4 compatibility

---

inc/backend.class.php
inc/backendcsv.class.php

Fix undefined index with php 7.4
See #188 #184

fix(core): fix undefined properties

---

inc/entityinjection.class.php

Internal ref: 20897.
Replace #214, specific code was needed for some recursive cases.
Add code to handle updates as they were ignored in previous code.

Fix updating entities

---

inc/session.class.php

Using path defined in based_config for installation with specific path for files

Fix issue #198

---

inc/commoninjectionlib.class.php

Ignore ```date_creation``` already manage by GLPI core
Prevent error on update

fix(core): ingore date_creation manage by core

---

inc/tasktemplateinjection.class.php
setup.php

Add TaskTemplate integration
Internal : 22192
depends on : https://github.com/glpi-project/glpi/pull/9146

Feat : Task template

---

inc/certificateinjection.class.php
setup.php

Implements certificate injection #151

Add certificate injection capability; closes #151

---

inc/commoninjectionlib.class.php

Fix ```Infocom``` injection
Fix ```mainitemtype``` injection on update
see !23794

fix(injection): fix Infocom injection and injection on update

---

inc/commoninjectionlib.class.php

global fix of CommonDBChild injection

fix(injection): global fix of CommonDBChild injection

---

inc/networknameinjection.class.php

Prevent duplicate IP Adress injection 
Fix duplicate IP : #240

fix(injection): prevent duplicate IP Adress

---

inc/model.class.php

Adds to the injection report, a new table "Global Report" with :
- number of lines in the source file
- number of lines Added
- number of lines Updated
- number of Errors by reconciliation key

feat: add global report (with DEEZER)

---

inc/phoneinjection.class.php

Fix duplicate search option name
one for the phone name and one for the domain name
fix : !26345

fix(searchoption): fix search option name for mapping

---

inc/computerinjection.class.php

blacklist some SO (prevent multiple ```name``` entry)
- Rack
- Domain
- Agent

fix(searchoption): blacklist some SO

---

inc/itilfollowuptemplateinjection.class.php
inc/tasktemplateinjection.class.php
setup.php

Hello,
I would like to submit for validation the changes I made to the plugins to add the ability to inject ITIL follow up template.
I updated the "setup.php" file and added "itilfollowuptemplate.class.php" file.
Thank you.
Antoine MAHIEU

Itil followup template added

---

inc/infocominjection.class.php

Hey there,
Just it gives dropdown format.
I suppose it will be included on core:
https://github.com/glpi-project/glpi/pull/14790

Include Business criticity.

---

inc/commoninjectionlib.class.php
inc/modelcsv.class.php
inc/networkportinjection.class.php
inc/profile.class.php
inc/softwarelicenseinjection.class.php
inc/softwareversioninjection.class.php
inc/userinjection.class.php

Raw queries containing user inputs should not be migrated to doQuery yet.

Revert doQuery changes

---

CHANGELOG.md
front/clientinjection.form.php
front/model.form.php
inc/clientinjection.class.php

Display max upload size
Fix https://github.com/pluginsGLPI/datainjection/issues/357

feat(Injection): Display max upload size

---

CHANGELOG.md
inc/userinjection.class.php

add ```default_entity``` to `User` injection mapping

Feat(User): add default_entity

---

datainjection.xml

- It fixes # (issue number, if applicable)

Fix(Buyild): fix artifiact name

---

datainjection.xml

- It fixes # (issue number, if applicable)

Fix(Build): fix artifiact name

---

CHANGELOG.md
inc/databaseinstanceinjection.class.php
inc/deviceharddriveinjection.class.php
inc/devicememoryinjection.class.php
inc/devicemotherboardinjection.class.php
inc/deviceprocessorinjection.class.php
inc/item_operatingsysteminjection.class.php
inc/item_softwarelicenseinjection.class.php
inc/networknameinjection.class.php

- It fixes !36122
Fix des itemtypes manquant dans les method connectdTo des classe d'injection

Fix missing itemtype in connectedTo method

---

inc/item_softwarelicenseinjection.class.php

- It fixes !36122
The computer mapping field was duplicated because the wrong item table was returned

Fix duplicated itemtype

---

CHANGELOG.md
inc/commoninjectionlib.class.php

Escape data when check if already exist
Like `effectiveaddOrUpdate`
Fix !36218

Fix(Core): escape data when check if already exist

---

.github/dependabot.yml

Enable dependabot for `10.0/bugfixes` branch

Enhanced depandabot scope v3

---

.stylelintrc.js
eslint.config.mjs
public/css/datainjection.css

add lint config for `eslint` and `stylelint`

Feat(Build): add stylelint and eslint
